/**
 * 1Password Connect
 * API interface for the 1Password Connect server.
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: support@1password.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
* The recipe is used in conjunction with the \"generate\" property to set the character set used to generate a new secure value
*/
export class GeneratorRecipe {
    /**
    * Length of the generated value
    */
    'length'?: number;
    'characterSets'?: Array<GeneratorRecipe.CharacterSetsEnum>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "length",
            "baseName": "length",
            "type": "number"
        },
        {
            "name": "characterSets",
            "baseName": "characterSets",
            "type": "Array<GeneratorRecipe.CharacterSetsEnum>"
        }    ];

    static getAttributeTypeMap() {
        return GeneratorRecipe.attributeTypeMap;
    }
}

export namespace GeneratorRecipe {
    export enum CharacterSetsEnum {
        Letters = <any> 'LETTERS',
        Digits = <any> 'DIGITS',
        Symbols = <any> 'SYMBOLS'
    }
}
