name: Pull Request Lint & Test

on:
    pull_request:
        types: [opened, reopened]

jobs:
    lintAndTest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Test with Node.js Latest LTS
              uses: actions/setup-node@v1
              with:
                  # Latest LTS version
                  node-version: '12.x'
            - name: Cache NPM modules
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: build-cache-${{ github.base_ref }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      build-cache-${{ github.base_ref }}-
            - run: npm ci
            - run: npm run lint
            - run: npm test
