name: Release SDK if needed

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.head.ref, 'release/')
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create Release tag
        id: create-tag
        env:
          PR_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          release_tag=$(echo "$PR_REF" | cut -d "/" -f2)
          echo "::set-output name=release-tag::$release_tag"
      - name: Make new release
        uses: step-security/release-action@a0d8e0f90f554c15366ca2c9046bf4090d24adbe # v1.21.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.create-tag.outputs.release-tag }}
          commit: main
          body: ${{ github.event.pull_request.body }}
